//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPrintSolutionsServiceBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertiserTest
    {
        public long SlNo { get; set; }
        public Nullable<int> AdvertiserID { get; set; }
        public string AdvertiserName { get; set; }
        public string PrimaryRegion { get; set; }
        public string MembershipStatus { get; set; }
        public Nullable<int> FeedID { get; set; }
        public string FeedName { get; set; }
        public string Language { get; set; }
        public string Vertical { get; set; }
        public Nullable<System.DateTime> LastImported { get; set; }
        public Nullable<System.DateTime> LastChecked { get; set; }
        public Nullable<int> No_Of_Products { get; set; }
        public string URL { get; set; }
    }
}
