//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPrintSolutionsServiceBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertiser
    {
        public long SlNo { get; set; }
        public Nullable<int> Advertiser_ID { get; set; }
        public string Advertiser_Name { get; set; }
        public string Primary_Region { get; set; }
        public string Membership_Status { get; set; }
        public Nullable<int> Feed_ID { get; set; }
        public string Feed_Name { get; set; }
        public string Language { get; set; }
        public string Vertical { get; set; }
        public Nullable<System.DateTime> Last_Imported { get; set; }
        public Nullable<System.DateTime> Last_Checked { get; set; }
        public Nullable<int> No_of_products { get; set; }
        public string URL { get; set; }
    }
}
