//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPrintSolutionsServiceBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvretiserCommission
    {
        public int AdvertiserId { get; set; }
        public string Commission_Group { get; set; }
        public Nullable<decimal> Commission_Percent { get; set; }
    }
}
