//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPrintSolutionsServiceBL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MprintSolutionServiceBlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MprintSolutionServiceBlResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPrintSolutionsServiceBL.MprintSolutionServiceBlResource", typeof(MprintSolutionServiceBlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdvertiserUrl.
        /// </summary>
        internal static string AdvertiserUrl {
            get {
                return ResourceManager.GetString("AdvertiserUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %2C.
        /// </summary>
        internal static string CommaDelimeter {
            get {
                return ResourceManager.GetString("CommaDelimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End from DownloadAdvertiser.
        /// </summary>
        internal static string EndDownloadAdvertiser {
            get {
                return ResourceManager.GetString("EndDownloadAdvertiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End from  fecthing advertiser list detail..
        /// </summary>
        internal static string EndFecthingAdvertiserListDetail {
            get {
                return ResourceManager.GetString("EndFecthingAdvertiserListDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End from inserting advertiser list detail..
        /// </summary>
        internal static string EndInsertAdvertiserListDetail {
            get {
                return ResourceManager.GetString("EndInsertAdvertiserListDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End from update advertiser list detail..
        /// </summary>
        internal static string EndUpdateAdvertiserListDetail {
            get {
                return ResourceManager.GetString("EndUpdateAdvertiserListDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception from DownloadAdvertiser.
        /// </summary>
        internal static string ExceptionDownloadAdvertiser {
            get {
                return ResourceManager.GetString("ExceptionDownloadAdvertiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception from fecthing advertiser list detail..
        /// </summary>
        internal static string ExceptionFecthingAdvertiserListDetail {
            get {
                return ResourceManager.GetString("ExceptionFecthingAdvertiserListDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception from inserting advertiser list detail..
        /// </summary>
        internal static string ExceptionInsertAdvertiserListDetail {
            get {
                return ResourceManager.GetString("ExceptionInsertAdvertiserListDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception from update advertiser list detail..
        /// </summary>
        internal static string ExceptionUpdateAdvertiserListDetail {
            get {
                return ResourceManager.GetString("ExceptionUpdateAdvertiserListDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedId.
        /// </summary>
        internal static string FeedId {
            get {
                return ResourceManager.GetString("FeedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedName.
        /// </summary>
        internal static string FeedName {
            get {
                return ResourceManager.GetString("FeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        internal static string FeedNameValue {
            get {
                return ResourceManager.GetString("FeedNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://productdata.awin.com/datafeed/download/apikey/77dd7588b893cbfdd0b662fcce5f471c/fid//format/csv/language/en/delimiter/%2C/compression/none/adultcontent/1/columns/aw_deep_link,product_name,aw_product_id,merchant_product_id,merchant_image_url,description,merchant_category,search_price,merchant_name,merchant_id,category_name,category_id,aw_image_url,currency,store_price,delivery_cost,merchant_deep_link,language,last_updated,display_price,data_feed_id,brand_name,brand_id,colour,product_short_description, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FeedUrl {
            get {
                return ResourceManager.GetString("FeedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM ADVERTISER WHERE MEMBERSHIPSTATUS = &apos;active &apos;.
        /// </summary>
        internal static string GetActiveAdvertisers {
            get {
                return ResourceManager.GetString("GetActiveAdvertisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gzip.
        /// </summary>
        internal static string Gzip {
            get {
                return ResourceManager.GetString("Gzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert_Advertiser.
        /// </summary>
        internal static string Insert_AdvertiserList {
            get {
                return ResourceManager.GetString("Insert_AdvertiserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastImported.
        /// </summary>
        internal static string LastImported {
            get {
                return ResourceManager.GetString("LastImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MembershipStatus.
        /// </summary>
        internal static string MembershipStatus {
            get {
                return ResourceManager.GetString("MembershipStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @dt.
        /// </summary>
        internal static string Parameter_dt {
            get {
                return ResourceManager.GetString("Parameter_dt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReewuDbCon.
        /// </summary>
        internal static string ReewuDbCon {
            get {
                return ResourceManager.GetString("ReewuDbCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start in DownloadAdvertiser.
        /// </summary>
        internal static string StartDownloadAdvertiser {
            get {
                return ResourceManager.GetString("StartDownloadAdvertiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start in fecthing advertiser list detail..
        /// </summary>
        internal static string StartFecthingAdvertiserListDetail {
            get {
                return ResourceManager.GetString("StartFecthingAdvertiserListDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start in inserting advertiser list detail..
        /// </summary>
        internal static string StartInsertAdvertiserListDetail {
            get {
                return ResourceManager.GetString("StartInsertAdvertiserListDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start in update advertiser list detail..
        /// </summary>
        internal static string StartUpdateAdvertiserListDetail {
            get {
                return ResourceManager.GetString("StartUpdateAdvertiserListDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update_AdvertiserList.
        /// </summary>
        internal static string Update_AdvertiserList {
            get {
                return ResourceManager.GetString("Update_AdvertiserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://productdata.awin.com/datafeed/download/apikey/77dd7588b893cbfdd0b662fcce5f471c/fid//format/csv/language/en/delimiter/%2C/compression/none/adultcontent/1/columns/Aw_Deep_Link,Product_Name,Aw_Product_Id,Merchant_Product_Id,Merchant_Image_Url,Description,Merchant_Category,Search_Price,Merchant_Name,Merchant_Id,Category_Name,Category_Id,Aw_Image_Url,Currency,Store_Price,Delivery_Cost,Merchant_Deep_Link,Language,Last_Updated,Display_Price,Data_Feed_Id,	Brand_Name,Brand_Id,Colour,Product_Short_Description [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
    }
}
