//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPrintSolutionsServiceBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFeed
    {
        public long SiNo { get; set; }
        public string Aw_Deep_Link { get; set; }
        public string Product_Name { get; set; }
        public Nullable<long> Aw_Product_Id { get; set; }
        public string Merchant_Product_Id { get; set; }
        public string Merchant_Image_Url { get; set; }
        public string Description { get; set; }
        public string Merchant_Category { get; set; }
        public Nullable<decimal> Search_Price { get; set; }
        public string Merchant_Name { get; set; }
        public Nullable<int> Merchant_Id { get; set; }
        public string Category_Name { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public string Aw_Image_Url { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Store_Price { get; set; }
        public string Delivery_Cost { get; set; }
        public string Merchant_Deep_Link { get; set; }
        public string Language { get; set; }
        public string Last_Updated { get; set; }
        public string Display_Price { get; set; }
        public Nullable<int> Data_Feed_Id { get; set; }
        public string Brand_Name { get; set; }
        public Nullable<int> Brand_Id { get; set; }
        public string Colour { get; set; }
        public string Product_Short_Description { get; set; }
        public string Specifications { get; set; }
        public string Condition { get; set; }
        public string Product_Model { get; set; }
        public string Model_Number { get; set; }
        public string Dimensions { get; set; }
        public string Keywords { get; set; }
        public string Promotional_Text { get; set; }
        public string Product_Type { get; set; }
        public string Commission_Group { get; set; }
        public string Merchant_Product_Category_Path { get; set; }
        public string Merchant_Product_Second_Category { get; set; }
        public string Merchant_Product_Third_Category { get; set; }
        public Nullable<decimal> Rrp_Price { get; set; }
        public Nullable<decimal> Saving { get; set; }
        public string Savings_Percent { get; set; }
        public Nullable<decimal> Base_Price { get; set; }
        public Nullable<decimal> Base_Price_Amount { get; set; }
        public string Base_Price_Text { get; set; }
        public string Product_Price_Old { get; set; }
        public string Delivery_Restrictions { get; set; }
        public Nullable<decimal> Delivery_Weight { get; set; }
        public string Warranty { get; set; }
        public string Terms_Of_Contract { get; set; }
        public string Delivery_Time { get; set; }
        public Nullable<int> In_Stock { get; set; }
        public Nullable<int> Stock_Quantity { get; set; }
        public Nullable<System.DateTime> Valid_From { get; set; }
        public Nullable<System.DateTime> Valid_To { get; set; }
        public Nullable<int> Is_For_Sale { get; set; }
        public Nullable<int> Web_Offer { get; set; }
        public Nullable<int> Pre_Order { get; set; }
        public string Stock_Status { get; set; }
        public string Size_Stock_Status { get; set; }
        public string Size_Stock_Amount { get; set; }
        public string Merchant_Thumb_Url { get; set; }
        public string Large_Image { get; set; }
        public string Alternate_Image { get; set; }
        public string Aw_Thumb_Url { get; set; }
        public string Alternate_Image_Two { get; set; }
        public string Alternate_Image_Three { get; set; }
        public string Alternate_Image_Four { get; set; }
        public string Reviews { get; set; }
        public string Average_Rating { get; set; }
        public string Rating { get; set; }
        public string Number_Available { get; set; }
        public string Custom_1 { get; set; }
        public string Custom_2 { get; set; }
        public string Custom_3 { get; set; }
        public string Custom_4 { get; set; }
        public string Custom_5 { get; set; }
        public string Custom_6 { get; set; }
        public string Custom_7 { get; set; }
        public string Custom_8 { get; set; }
        public string Custom_9 { get; set; }
        public string Ean { get; set; }
        public string Isbn { get; set; }
        public string Upc { get; set; }
        public string Mpn { get; set; }
        public string Parent_Product_Id { get; set; }
        public string Product_GTIN { get; set; }
        public string Basket_Link { get; set; }
    }
}
